[package]
name = "world-tax"
version = "0.1.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
serde_derive = "1.0.216"
serde_json = "1.0.133"
log = "0.4"
env_logger = "0.11"
rust_iso3166 = "0.1.13"
thiserror = "2.0.9"